### ISSUE TITLE
bcrypto: build error with gmp

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#148]
I was attempting to build hsd using the Dockerfile. 

If I build with bcrypto 3.1.3 or above, I receive the following build error with the gist of cannot find file gmp.h. I attempted to fix this issue by installing gmp-dev as seen in #147, which removes the build issues from the building of the dockerfile, but still returns an: ```Error: Bcrypto bindings were not built```

Looking for some suggestions on how to fix this. Additionally, when I pegged bcrypto to 3.1.2, I had 0 build issues and hsd worked just as fine as before. 

EDIT: I was able to successfully get bcrypto 3.1.3+ to compile on a standard Debian image with libgmp3-dev installed. My guess is that the compilation error has something to do with Alpine versions use musl clib. If bcrypto doesn't play well with that, we should probably switch the "official" docker image over to a Debian version of node rather than Alpine going forward. 

Logs from a 3.1.5 bcrypto install on ```node:alpine``` without gmp installed:
```
make: Entering directory '/code/node_modules/bcrypto/build'
  CC(target) Release/obj.target/bcrypto/src/aead/aead.o
  CC(target) Release/obj.target/bcrypto/src/aes/aes.o
  CC(target) Release/obj.target/bcrypto/src/blake2b/blake2b.o
  CC(target) Release/obj.target/bcrypto/src/blake2s/blake2s.o
  CC(target) Release/obj.target/bcrypto/src/chacha20/chacha20.o
  CC(target) Release/obj.target/bcrypto/src/dsa/dsa.o
  CC(target) Release/obj.target/bcrypto/src/ecdsa/ecdsa.o
  CC(target) Release/obj.target/bcrypto/src/ed25519/ed25519.o
  CC(target) Release/obj.target/bcrypto/src/ed448/arch_32/f_impl.o
  CC(target) Release/obj.target/bcrypto/src/ed448/curve448.o
  CC(target) Release/obj.target/bcrypto/src/ed448/curve448_tables.o
  CC(target) Release/obj.target/bcrypto/src/ed448/eddsa.o
  CC(target) Release/obj.target/bcrypto/src/ed448/f_generic.o
  CC(target) Release/obj.target/bcrypto/src/ed448/scalar.o
  CC(target) Release/obj.target/bcrypto/src/murmur3/murmur3.o
  CC(target) Release/obj.target/bcrypto/src/pbkdf2/pbkdf2.o
  CC(target) Release/obj.target/bcrypto/src/poly1305/poly1305.o
  CC(target) Release/obj.target/bcrypto/src/random/random.o
  CC(target) Release/obj.target/bcrypto/src/rsa/rsa.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/insecure_memzero.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/sha256.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/scrypt.o
  CC(target) Release/obj.target/bcrypto/src/secp256k1/src/secp256k1.o
In file included from ../src/secp256k1/src/num.h:17,
                 from ../src/secp256k1/src/num_impl.h:14,
                 from ../src/secp256k1/src/secp256k1.c:10:
../src/secp256k1/src/num_gmp.h:10:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
make: Leaving directory '/code/node_modules/bcrypto/build'
make: *** [bcrypto.target.mk:241: Release/obj.target/bcrypto/src/secp256k1/src/secp256k1.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /code/node_modules/bcrypto
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed.
```

Logs from a bcrypto install with gmp-dev installed on the docker image (Still results in bcrypto bindings not built): 
```
> bcrypto@3.1.5 install /code/node_modules/bcrypto
> node-gyp rebuild || echo 'Build failed.'

make: Entering directory '/code/node_modules/bcrypto/build'
  CC(target) Release/obj.target/bcrypto/src/aead/aead.o
  CC(target) Release/obj.target/bcrypto/src/aes/aes.o
  CC(target) Release/obj.target/bcrypto/src/blake2b/blake2b.o
  CC(target) Release/obj.target/bcrypto/src/blake2s/blake2s.o
  CC(target) Release/obj.target/bcrypto/src/chacha20/chacha20.o
  CC(target) Release/obj.target/bcrypto/src/dsa/dsa.o
  CC(target) Release/obj.target/bcrypto/src/ecdsa/ecdsa.o
  CC(target) Release/obj.target/bcrypto/src/ed25519/ed25519.o
  CC(target) Release/obj.target/bcrypto/src/ed448/arch_32/f_impl.o
  CC(target) Release/obj.target/bcrypto/src/ed448/curve448.o
  CC(target) Release/obj.target/bcrypto/src/ed448/curve448_tables.o
  CC(target) Release/obj.target/bcrypto/src/ed448/eddsa.o
  CC(target) Release/obj.target/bcrypto/src/ed448/f_generic.o
  CC(target) Release/obj.target/bcrypto/src/ed448/scalar.o
  CC(target) Release/obj.target/bcrypto/src/murmur3/murmur3.o
  CC(target) Release/obj.target/bcrypto/src/pbkdf2/pbkdf2.o
  CC(target) Release/obj.target/bcrypto/src/poly1305/poly1305.o
  CC(target) Release/obj.target/bcrypto/src/random/random.o
  CC(target) Release/obj.target/bcrypto/src/rsa/rsa.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/insecure_memzero.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/sha256.o
  CC(target) Release/obj.target/bcrypto/src/scrypt/scrypt.o
  CC(target) Release/obj.target/bcrypto/src/secp256k1/src/secp256k1.o
  CC(target) Release/obj.target/bcrypto/src/secp256k1/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/bcrypto/src/secp256k1/contrib/lax_der_privatekey_parsing.o
  CC(target) Release/obj.target/bcrypto/src/siphash/siphash.o
  CC(target) Release/obj.target/bcrypto/src/keccak/keccak.o
  CXX(target) Release/obj.target/bcrypto/src/aead.o
  CXX(target) Release/obj.target/bcrypto/src/aes.o
  CXX(target) Release/obj.target/bcrypto/src/bcrypto.o
  CXX(target) Release/obj.target/bcrypto/src/blake2b.o
  CXX(target) Release/obj.target/bcrypto/src/blake2s.o
  CXX(target) Release/obj.target/bcrypto/src/chacha20.o
  CXX(target) Release/obj.target/bcrypto/src/cipherbase.o
  CXX(target) Release/obj.target/bcrypto/src/dsa.o
  CXX(target) Release/obj.target/bcrypto/src/dsa_async.o
  CXX(target) Release/obj.target/bcrypto/src/ecdsa.o
  CXX(target) Release/obj.target/bcrypto/src/ed25519.o
  CXX(target) Release/obj.target/bcrypto/src/ed448.o
  CXX(target) Release/obj.target/bcrypto/src/hash160.o
  CXX(target) Release/obj.target/bcrypto/src/hash256.o
  CXX(target) Release/obj.target/bcrypto/src/keccak.o
  CXX(target) Release/obj.target/bcrypto/src/md4.o
  CXX(target) Release/obj.target/bcrypto/src/md5.o
  CXX(target) Release/obj.target/bcrypto/src/murmur3.o
  CXX(target) Release/obj.target/bcrypto/src/pbkdf2.o
  CXX(target) Release/obj.target/bcrypto/src/pbkdf2_async.o
  CXX(target) Release/obj.target/bcrypto/src/poly1305.o
  CXX(target) Release/obj.target/bcrypto/src/random.o
  CXX(target) Release/obj.target/bcrypto/src/ripemd160.o
  CXX(target) Release/obj.target/bcrypto/src/rsa.o
  CXX(target) Release/obj.target/bcrypto/src/rsa_async.o
  CXX(target) Release/obj.target/bcrypto/src/scrypt.o
  CXX(target) Release/obj.target/bcrypto/src/scrypt_async.o
  CXX(target) Release/obj.target/bcrypto/src/secp256k1.o
  CXX(target) Release/obj.target/bcrypto/src/sha1.o
  CXX(target) Release/obj.target/bcrypto/src/sha224.o
  CXX(target) Release/obj.target/bcrypto/src/sha256.o
  CXX(target) Release/obj.target/bcrypto/src/sha384.o
  CXX(target) Release/obj.target/bcrypto/src/sha512.o
  CXX(target) Release/obj.target/bcrypto/src/siphash.o
  CXX(target) Release/obj.target/bcrypto/src/whirlpool.o
  SOLINK_MODULE(target) Release/obj.target/bcrypto.node
  COPY Release/bcrypto.node
make: Leaving directory '/code/node_modules/bcrypto/build'
```

Also: attempting to change the Dockerfile to build on Node 10 did not fix any of the issues.

**Comment by kilpatty** [comment]
This is related to https://github.com/bcoin-org/bcrypto/issues/16, and looks like this commit: https://github.com/bcoin-org/bcrypto/commit/5d7cbcdb15a83f731827a3778d683c79cfc4b10a might just fix this.

**Comment by gpmidi** [comment]
Even with @kilpatty's patch merged I'm still having build issues with "Bindings for bcrypto were not built"

**Comment by kilpatty** [comment]
@gpmidi I think there have been some new updates to Bcrypto since, so I owe that PR some updates. Will push up another PR later this afternoon that should solve that issue!

**Comment by gpmidi** [comment]
I have it working now using the default, non-alpine image. It's probably the same sorta changes you made to yours.

**Comment by boymanjor** [comment]
The following commit fixes this issue: https://github.com/handshake-org/hsd/commit/7c172277476ea2a41501413f4f43a4a0a040b100. The commit was cherry-picked from #252.
